import { Inter } from "next/font/google";
import Head from "next/head";
import Inform from "@/components/ınform/ınform";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import styles from "./globals.module.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lokasyon Matematik | Ankara Özel Ders",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={styles.root}>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/Tittleicon.ico" />
      </Head>
      <body className={inter.className}>
        <Inform />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
