import { Inter } from "next/font/google";
import Header from "@/components/header/header";
import styles from "./globals.module.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Samet Hoca",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={styles.root}>
      <body className={inter.className}>
        <Header />
        {children}
        </body>
    </html>
  );
}
